//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuanCodeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BinhLuanCodeTable()
        {
            this.TraLoiCodeTables = new HashSet<TraLoiCodeTable>();
        }
    
        public int MaBnhLuanCode { get; set; }
        public Nullable<int> MaNguoiDang { get; set; }
        public Nullable<int> MaCode { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<bool> PhanQuyen { get; set; }
    
        public virtual AdminTable AdminTable { get; set; }
        public virtual NguoiDungTable NguoiDungTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraLoiCodeTable> TraLoiCodeTables { get; set; }
    }
}
