//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogTable()
        {
            this.NgonNgu_BlogTable = new HashSet<NgonNgu_BlogTable>();
        }
    
        public int MaBlog { get; set; }
        public string TenBlog { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public string AnhMinhHoa { get; set; }
    
        public virtual NguoiDungTable NguoiDungTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NgonNgu_BlogTable> NgonNgu_BlogTable { get; set; }
    }
}
