//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgonNguTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NgonNguTable()
        {
            this.NgonNgu_BlogTable = new HashSet<NgonNgu_BlogTable>();
            this.NgonNgu_CodeTable = new HashSet<NgonNgu_CodeTable>();
        }
    
        public int MaNgonNgu { get; set; }
        public string NgonNgu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NgonNgu_BlogTable> NgonNgu_BlogTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NgonNgu_CodeTable> NgonNgu_CodeTable { get; set; }
    }
}
