//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgonNgu_BlogTable
    {
        public int MaNgonNgu_Blog { get; set; }
        public Nullable<int> MaNgonNgu { get; set; }
        public Nullable<int> MaBlog { get; set; }
    
        public virtual BlogTable BlogTable { get; set; }
        public virtual NgonNguTable NgonNguTable { get; set; }
    }
}
