//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToanTable
    {
        public int MaThanhToan { get; set; }
        public Nullable<int> MaCode { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public Nullable<int> MaNguoiMua { get; set; }
    
        public virtual CodeTable CodeTable { get; set; }
    }
}
