//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraLoiCodeTable
    {
        public int MaTraLoiCode { get; set; }
        public Nullable<int> MaBinhLuanCode { get; set; }
        public Nullable<int> MaNguoiDang { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<bool> PhanQuyen { get; set; }
    
        public virtual AdminTable AdminTable { get; set; }
        public virtual BinhLuanCodeTable BinhLuanCodeTable { get; set; }
        public virtual NguoiDungTable NguoiDungTable { get; set; }
    }
}
